prof_:
    pattern:  /add
    defaults: { _controller: "NotemonprofUserBundle:Prof:add" }
    
prof_:
    pattern:  /
    defaults: { _controller: "NotemonprofUserBundle:Prof:index" }
    
prof_show:
    pattern:  /{id}/show
    defaults: { _controller: "NotemonprofUserBundle:Prof:show" }
    
prof_new:
    pattern:  /new
    defaults: { _controller: "NotemonprofUserBundle:Prof:new" }
    
prof_create:
    pattern:  /create
    defaults: { _controller: "NotemonprofUserBundle:Prof:create" }
    requirements: { _method: post }
    
prof_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NotemonprofUserBundle:Prof:edit" }
    
prof_update:
    pattern:  /{id}/update
    defaults: { _controller: "NotemonprofUserBundle:Prof:update" }
    requirements: { _method: post|put }
    
prof_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NotemonprofUserBundle:Prof:delete" }
    requirements: { _method: post|delete }    